version: '3'
services:
  db:
    image: mysql
    volumes:
      - dbdata:/var/lib/mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: banco
  
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    image: maddytec/spring_cloud-banco:1.0
    depends_on:
      - db
    ports:
      - 8090:8090

volumes:
  dbdata:
