version: '3.3'

services:
    backend:
      build:
        context: .
        dockerfile: Dockerfile
      image: maddytec/spring_cloud-gateway:1.0
      ports:
        - 8099:8099
      network_mode: "host"