version: '3.3'

services:
    backend:
      build:
        context: .
        dockerfile: Dockerfile
      image: maddytec/spring_cloud-efetivacao:1.0
      ports:
        - 8081:8081
      network_mode: "host"