version: '3.3'

services:
  redis:
    image: redis
    ports:
      - 6379:6379

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    image: maddytec/spring_cloud-feedback:1.0
    depends_on:
      - redis
    ports:
      - 8082:8082
    network_mode: "host"